name: Flutter CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: gradle
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
          channel: 'stable'
          cache: true
      - run: flutter pub get
      - run: flutter analyze .
      - run: flutter build apk --split-per-abi
      - run: flutter build web --release

      - name: app-armabi-v7a-release.apk
        uses: actions/upload-artifact@v2
        with:
          name: app-armabi-v7a-release
          path: build/app/outputs/apk/release/app-armabi-v7a-release.apk

      - name: app-arm64-v8a-release.apk
        uses: actions/upload-artifact@v2
        with:
          name: app-arm64-v8a-release
          path: build/app/outputs/apk/release/app-arm64-v8a-release.apk

      - name: app-x86_64-release.apk
        uses: actions/upload-artifact@v2
        with:
          name: app-x86_64-release
          path: build/app/outputs/apk/release/app-x86_64-release.apk

      - uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: build/web